/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

#ifndef IMAGES_H_
#define IMAGES_H_

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#define IMAGES  1

#ifndef IMAGES_T_
#define IMAGES_T_

typedef struct {
	const char *name;
	void *addr;
	size_t size;
	size_t inflated;
	bool compressed;
} image_t;

#endif
extern image_t images[];

extern uint8_t helenos_tga[];
extern size_t helenos_tga_size;

#endif
