/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

.data

.globl helenos_tga
.balign 8
.size helenos_tga, 38826
helenos_tga:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/aboutos/gfx/helenos.tga"

