/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

#include "images.h"

image_t images[] = {
	{
		.name = "helenos",
		.addr = (void *) helenos_tga,
		.size = 38826,
		.inflated = 38826,
		.compressed = false
	}
};

size_t helenos_tga_size = 38826;
