/***************************************
 * AUTO-GENERATED FILE, DO NOT EDIT!!! *
 * Generated by: tools/config.py       *
 ***************************************/

/* Platform */
#define PLATFORM amd64
#define PLATFORM_amd64

/* CPU type */
#define PROCESSOR opteron
#define PROCESSOR_opteron

/* Kernel memory model */
#define MEMORY_MODEL kernel
#define MEMORY_MODEL_kernel

/* RAM disk format */
#define RDFMT ext4fs
#define RDFMT_ext4fs

/* Kernel architecture */
#define KARCH amd64
#define KARCH_amd64

/* User space architecture */
#define UARCH amd64
#define UARCH_amd64

/* Boot architecture */
#define BARCH amd64
#define BARCH_amd64

/* Compiler */
#define COMPILER gcc_cross
#define COMPILER_gcc_cross

/* Fences */
#define CONFIG_FENCES_P4

/* IOMAP bitmap support */
#define CONFIG_IOMAP_BITMAP

/* ACPI support */
#define CONFIG_ACPI

/* Hierarchical page tables support */
#define CONFIG_PAGE_PT

/* Multiboot standard support */
#define CONFIG_MULTIBOOT

/* FPU support */
#define CONFIG_FPU

/* Support for SMP */
#define CONFIG_SMP

/* Debug build */
#define CONFIG_DEBUG

/* Track owner for futexes in userspace. */
#define CONFIG_DEBUG_FUTEX

/* Deadlock detection support for spinlocks */
#define CONFIG_DEBUG_SPINLOCK

/* Lazy FPU context switching */
#define CONFIG_FPU_LAZY

/* Support for Intel i8259 PIC */
#define CONFIG_I8259

/* Support for userspace debuggers */
#define CONFIG_UDEBUG

/* Kernel console support */
#define CONFIG_KCONSOLE

/* Kernel symbol information */
#define CONFIG_SYMTAB

/* Compile kernel tests */
#define CONFIG_TEST

/* Compress init data */
#define CONFIG_COMPRESSED_INIT

/* Input device class */
#define CONFIG_HID_IN generic
#define CONFIG_HID_IN_generic

/* Output device class */
#define CONFIG_HID_OUT generic
#define CONFIG_HID_OUT_generic

/* PC keyboard support */
#define CONFIG_PC_KBD

/* Support for PL011 UART */
#define CONFIG_PL011_UART

/* Support for NS16550 controller (kernel console) */
#define CONFIG_NS16550_KCON

/* Use NS16550 controller as serial input (kernel console) */
#define CONFIG_NS16550

/* Use NS16550 controller as dummy serial output (kernel console) */
#define CONFIG_NS16550_OUT

/* Support for i8042 controller */
#define CONFIG_I8042

/* Serial line input module */
#define CONFIG_SRLN

/* EGA support */
#define CONFIG_EGA

/* Framebuffer support */
#define CONFIG_FB

/* Default framebuffer mode */
#define CONFIG_BFB_MODE 1024x768
#define CONFIG_BFB_MODE_1024x768

/* Default framebuffer depth */
#define CONFIG_BFB_BPP 16
#define CONFIG_BFB_BPP_16

/* Window system */
#define CONFIG_WINSYS

/* Display double buffering */
#define CONFIG_DISP_DOUBLE_BUF

/* Client-side UI rendering */
#define CONFIG_UI_CS_RENDER

/* Dynamic linking support */
#define CONFIG_RTLD

/* Build shared libraries */
#define CONFIG_BUILD_SHARED_LIBS

/* Link against shared libraries */
#define CONFIG_USE_SHARED_LIBS

/* Include userspace unit tests (PCUT) */
#define CONFIG_PCUT_TESTS

/* Include development files (headers, libraries) */
#define CONFIG_DEVEL_FILES

/* Optimization level */
#define OPTIMIZATION 3
#define OPTIMIZATION_3

/* OHCI root hub port power switching */
#define OHCI_POWER_SWITCH ganged
#define OHCI_POWER_SWITCH_ganged

/* GRUB boot loader architecture */
#define GRUB_ARCH pc
#define GRUB_ARCH_pc

/* Default framebuffer width */
#define CONFIG_BFB_WIDTH 1024
#define CONFIG_BFB_WIDTH_1024

/* Default framebuffer height */
#define CONFIG_BFB_HEIGHT 768
#define CONFIG_BFB_HEIGHT_768

#define REVISION 12dd36c50
#define TIMESTAMP_UNIX 1738811592
#define TIMESTAMP 2025-02-06 11:13:12
