/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

.data

.globl frame01_tga_gz
.balign 8
.size frame01_tga_gz, 16065
frame01_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame01.tga.gz"

.globl frame02_tga_gz
.balign 8
.size frame02_tga_gz, 16044
frame02_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame02.tga.gz"

.globl frame03_tga_gz
.balign 8
.size frame03_tga_gz, 15948
frame03_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame03.tga.gz"

.globl frame04_tga_gz
.balign 8
.size frame04_tga_gz, 15891
frame04_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame04.tga.gz"

.globl frame05_tga_gz
.balign 8
.size frame05_tga_gz, 15800
frame05_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame05.tga.gz"

.globl frame06_tga_gz
.balign 8
.size frame06_tga_gz, 15803
frame06_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame06.tga.gz"

.globl frame07_tga_gz
.balign 8
.size frame07_tga_gz, 15812
frame07_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame07.tga.gz"

.globl frame08_tga_gz
.balign 8
.size frame08_tga_gz, 15670
frame08_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame08.tga.gz"

.globl frame09_tga_gz
.balign 8
.size frame09_tga_gz, 15698
frame09_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame09.tga.gz"

.globl frame10_tga_gz
.balign 8
.size frame10_tga_gz, 15748
frame10_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame10.tga.gz"

.globl frame11_tga_gz
.balign 8
.size frame11_tga_gz, 15902
frame11_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame11.tga.gz"

.globl frame12_tga_gz
.balign 8
.size frame12_tga_gz, 15945
frame12_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame12.tga.gz"

.globl frame13_tga_gz
.balign 8
.size frame13_tga_gz, 16002
frame13_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame13.tga.gz"

.globl frame14_tga_gz
.balign 8
.size frame14_tga_gz, 16210
frame14_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame14.tga.gz"

.globl frame15_tga_gz
.balign 8
.size frame15_tga_gz, 16061
frame15_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame15.tga.gz"

.globl frame16_tga_gz
.balign 8
.size frame16_tga_gz, 15991
frame16_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame16.tga.gz"

.globl frame17_tga_gz
.balign 8
.size frame17_tga_gz, 16085
frame17_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame17.tga.gz"

.globl frame18_tga_gz
.balign 8
.size frame18_tga_gz, 15940
frame18_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame18.tga.gz"

.globl frame19_tga_gz
.balign 8
.size frame19_tga_gz, 15819
frame19_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame19.tga.gz"

.globl frame20_tga_gz
.balign 8
.size frame20_tga_gz, 15805
frame20_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame20.tga.gz"

.globl frame21_tga_gz
.balign 8
.size frame21_tga_gz, 15762
frame21_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame21.tga.gz"

.globl frame22_tga_gz
.balign 8
.size frame22_tga_gz, 15711
frame22_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame22.tga.gz"

.globl frame23_tga_gz
.balign 8
.size frame23_tga_gz, 15672
frame23_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame23.tga.gz"

.globl frame24_tga_gz
.balign 8
.size frame24_tga_gz, 15717
frame24_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame24.tga.gz"

.globl frame25_tga_gz
.balign 8
.size frame25_tga_gz, 15806
frame25_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame25.tga.gz"

.globl frame26_tga_gz
.balign 8
.size frame26_tga_gz, 15924
frame26_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame26.tga.gz"

.globl frame27_tga_gz
.balign 8
.size frame27_tga_gz, 15926
frame27_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame27.tga.gz"

.globl frame28_tga_gz
.balign 8
.size frame28_tga_gz, 16041
frame28_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame28.tga.gz"

.globl frame29_tga_gz
.balign 8
.size frame29_tga_gz, 16095
frame29_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame29.tga.gz"

.globl frame30_tga_gz
.balign 8
.size frame30_tga_gz, 16021
frame30_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx/frame30.tga.gz"

