/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

#ifndef IMAGES_H_
#define IMAGES_H_

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#define IMAGES  30

#ifndef IMAGES_T_
#define IMAGES_T_

typedef struct {
	const char *name;
	void *addr;
	size_t size;
	size_t inflated;
	bool compressed;
} image_t;

#endif
extern image_t images[];

extern uint8_t frame01_tga_gz[];
extern size_t frame01_tga_gz_size;
extern uint8_t frame02_tga_gz[];
extern size_t frame02_tga_gz_size;
extern uint8_t frame03_tga_gz[];
extern size_t frame03_tga_gz_size;
extern uint8_t frame04_tga_gz[];
extern size_t frame04_tga_gz_size;
extern uint8_t frame05_tga_gz[];
extern size_t frame05_tga_gz_size;
extern uint8_t frame06_tga_gz[];
extern size_t frame06_tga_gz_size;
extern uint8_t frame07_tga_gz[];
extern size_t frame07_tga_gz_size;
extern uint8_t frame08_tga_gz[];
extern size_t frame08_tga_gz_size;
extern uint8_t frame09_tga_gz[];
extern size_t frame09_tga_gz_size;
extern uint8_t frame10_tga_gz[];
extern size_t frame10_tga_gz_size;
extern uint8_t frame11_tga_gz[];
extern size_t frame11_tga_gz_size;
extern uint8_t frame12_tga_gz[];
extern size_t frame12_tga_gz_size;
extern uint8_t frame13_tga_gz[];
extern size_t frame13_tga_gz_size;
extern uint8_t frame14_tga_gz[];
extern size_t frame14_tga_gz_size;
extern uint8_t frame15_tga_gz[];
extern size_t frame15_tga_gz_size;
extern uint8_t frame16_tga_gz[];
extern size_t frame16_tga_gz_size;
extern uint8_t frame17_tga_gz[];
extern size_t frame17_tga_gz_size;
extern uint8_t frame18_tga_gz[];
extern size_t frame18_tga_gz_size;
extern uint8_t frame19_tga_gz[];
extern size_t frame19_tga_gz_size;
extern uint8_t frame20_tga_gz[];
extern size_t frame20_tga_gz_size;
extern uint8_t frame21_tga_gz[];
extern size_t frame21_tga_gz_size;
extern uint8_t frame22_tga_gz[];
extern size_t frame22_tga_gz_size;
extern uint8_t frame23_tga_gz[];
extern size_t frame23_tga_gz_size;
extern uint8_t frame24_tga_gz[];
extern size_t frame24_tga_gz_size;
extern uint8_t frame25_tga_gz[];
extern size_t frame25_tga_gz_size;
extern uint8_t frame26_tga_gz[];
extern size_t frame26_tga_gz_size;
extern uint8_t frame27_tga_gz[];
extern size_t frame27_tga_gz_size;
extern uint8_t frame28_tga_gz[];
extern size_t frame28_tga_gz_size;
extern uint8_t frame29_tga_gz[];
extern size_t frame29_tga_gz_size;
extern uint8_t frame30_tga_gz[];
extern size_t frame30_tga_gz_size;

#endif
