/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

.data

.globl frame01t_tga_gz
.balign 8
.size frame01t_tga_gz, 505
frame01t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame01t.tga.gz"

.globl frame02t_tga_gz
.balign 8
.size frame02t_tga_gz, 508
frame02t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame02t.tga.gz"

.globl frame03t_tga_gz
.balign 8
.size frame03t_tga_gz, 507
frame03t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame03t.tga.gz"

.globl frame04t_tga_gz
.balign 8
.size frame04t_tga_gz, 510
frame04t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame04t.tga.gz"

.globl frame05t_tga_gz
.balign 8
.size frame05t_tga_gz, 511
frame05t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame05t.tga.gz"

.globl frame06t_tga_gz
.balign 8
.size frame06t_tga_gz, 509
frame06t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame06t.tga.gz"

.globl frame07t_tga_gz
.balign 8
.size frame07t_tga_gz, 505
frame07t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame07t.tga.gz"

.globl frame08t_tga_gz
.balign 8
.size frame08t_tga_gz, 499
frame08t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame08t.tga.gz"

.globl frame09t_tga_gz
.balign 8
.size frame09t_tga_gz, 507
frame09t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame09t.tga.gz"

.globl frame10t_tga_gz
.balign 8
.size frame10t_tga_gz, 509
frame10t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame10t.tga.gz"

.globl frame11t_tga_gz
.balign 8
.size frame11t_tga_gz, 507
frame11t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame11t.tga.gz"

.globl frame12t_tga_gz
.balign 8
.size frame12t_tga_gz, 509
frame12t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame12t.tga.gz"

.globl frame13t_tga_gz
.balign 8
.size frame13t_tga_gz, 502
frame13t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame13t.tga.gz"

.globl frame14t_tga_gz
.balign 8
.size frame14t_tga_gz, 504
frame14t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame14t.tga.gz"

.globl frame15t_tga_gz
.balign 8
.size frame15t_tga_gz, 502
frame15t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame15t.tga.gz"

.globl frame16t_tga_gz
.balign 8
.size frame16t_tga_gz, 501
frame16t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame16t.tga.gz"

.globl frame17t_tga_gz
.balign 8
.size frame17t_tga_gz, 500
frame17t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame17t.tga.gz"

.globl frame18t_tga_gz
.balign 8
.size frame18t_tga_gz, 508
frame18t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame18t.tga.gz"

.globl frame19t_tga_gz
.balign 8
.size frame19t_tga_gz, 508
frame19t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame19t.tga.gz"

.globl frame20t_tga_gz
.balign 8
.size frame20t_tga_gz, 507
frame20t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame20t.tga.gz"

.globl frame21t_tga_gz
.balign 8
.size frame21t_tga_gz, 511
frame21t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame21t.tga.gz"

.globl frame22t_tga_gz
.balign 8
.size frame22t_tga_gz, 508
frame22t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame22t.tga.gz"

.globl frame23t_tga_gz
.balign 8
.size frame23t_tga_gz, 500
frame23t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame23t.tga.gz"

.globl frame24t_tga_gz
.balign 8
.size frame24t_tga_gz, 504
frame24t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame24t.tga.gz"

.globl frame25t_tga_gz
.balign 8
.size frame25t_tga_gz, 508
frame25t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame25t.tga.gz"

.globl frame26t_tga_gz
.balign 8
.size frame26t_tga_gz, 510
frame26t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame26t.tga.gz"

.globl frame27t_tga_gz
.balign 8
.size frame27t_tga_gz, 509
frame27t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame27t.tga.gz"

.globl frame28t_tga_gz
.balign 8
.size frame28t_tga_gz, 514
frame28t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame28t.tga.gz"

.globl frame29t_tga_gz
.balign 8
.size frame29t_tga_gz, 498
frame29t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame29t.tga.gz"

.globl frame30t_tga_gz
.balign 8
.size frame30t_tga_gz, 509
frame30t_tga_gz:
	.incbin "/home/zyc/code/build/amd64/../../helenos/uspace/app/barber/gfx-tiny/frame30t.tga.gz"

