/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

#include "images_tiny.h"

image_t image_tinys[] = {
	{
		.name = "frame01t.tga",
		.addr = (void *) frame01t_tga_gz,
		.size = 505,
		.inflated = 505,
		.compressed = false
	},
	{
		.name = "frame02t.tga",
		.addr = (void *) frame02t_tga_gz,
		.size = 508,
		.inflated = 508,
		.compressed = false
	},
	{
		.name = "frame03t.tga",
		.addr = (void *) frame03t_tga_gz,
		.size = 507,
		.inflated = 507,
		.compressed = false
	},
	{
		.name = "frame04t.tga",
		.addr = (void *) frame04t_tga_gz,
		.size = 510,
		.inflated = 510,
		.compressed = false
	},
	{
		.name = "frame05t.tga",
		.addr = (void *) frame05t_tga_gz,
		.size = 511,
		.inflated = 511,
		.compressed = false
	},
	{
		.name = "frame06t.tga",
		.addr = (void *) frame06t_tga_gz,
		.size = 509,
		.inflated = 509,
		.compressed = false
	},
	{
		.name = "frame07t.tga",
		.addr = (void *) frame07t_tga_gz,
		.size = 505,
		.inflated = 505,
		.compressed = false
	},
	{
		.name = "frame08t.tga",
		.addr = (void *) frame08t_tga_gz,
		.size = 499,
		.inflated = 499,
		.compressed = false
	},
	{
		.name = "frame09t.tga",
		.addr = (void *) frame09t_tga_gz,
		.size = 507,
		.inflated = 507,
		.compressed = false
	},
	{
		.name = "frame10t.tga",
		.addr = (void *) frame10t_tga_gz,
		.size = 509,
		.inflated = 509,
		.compressed = false
	},
	{
		.name = "frame11t.tga",
		.addr = (void *) frame11t_tga_gz,
		.size = 507,
		.inflated = 507,
		.compressed = false
	},
	{
		.name = "frame12t.tga",
		.addr = (void *) frame12t_tga_gz,
		.size = 509,
		.inflated = 509,
		.compressed = false
	},
	{
		.name = "frame13t.tga",
		.addr = (void *) frame13t_tga_gz,
		.size = 502,
		.inflated = 502,
		.compressed = false
	},
	{
		.name = "frame14t.tga",
		.addr = (void *) frame14t_tga_gz,
		.size = 504,
		.inflated = 504,
		.compressed = false
	},
	{
		.name = "frame15t.tga",
		.addr = (void *) frame15t_tga_gz,
		.size = 502,
		.inflated = 502,
		.compressed = false
	},
	{
		.name = "frame16t.tga",
		.addr = (void *) frame16t_tga_gz,
		.size = 501,
		.inflated = 501,
		.compressed = false
	},
	{
		.name = "frame17t.tga",
		.addr = (void *) frame17t_tga_gz,
		.size = 500,
		.inflated = 500,
		.compressed = false
	},
	{
		.name = "frame18t.tga",
		.addr = (void *) frame18t_tga_gz,
		.size = 508,
		.inflated = 508,
		.compressed = false
	},
	{
		.name = "frame19t.tga",
		.addr = (void *) frame19t_tga_gz,
		.size = 508,
		.inflated = 508,
		.compressed = false
	},
	{
		.name = "frame20t.tga",
		.addr = (void *) frame20t_tga_gz,
		.size = 507,
		.inflated = 507,
		.compressed = false
	},
	{
		.name = "frame21t.tga",
		.addr = (void *) frame21t_tga_gz,
		.size = 511,
		.inflated = 511,
		.compressed = false
	},
	{
		.name = "frame22t.tga",
		.addr = (void *) frame22t_tga_gz,
		.size = 508,
		.inflated = 508,
		.compressed = false
	},
	{
		.name = "frame23t.tga",
		.addr = (void *) frame23t_tga_gz,
		.size = 500,
		.inflated = 500,
		.compressed = false
	},
	{
		.name = "frame24t.tga",
		.addr = (void *) frame24t_tga_gz,
		.size = 504,
		.inflated = 504,
		.compressed = false
	},
	{
		.name = "frame25t.tga",
		.addr = (void *) frame25t_tga_gz,
		.size = 508,
		.inflated = 508,
		.compressed = false
	},
	{
		.name = "frame26t.tga",
		.addr = (void *) frame26t_tga_gz,
		.size = 510,
		.inflated = 510,
		.compressed = false
	},
	{
		.name = "frame27t.tga",
		.addr = (void *) frame27t_tga_gz,
		.size = 509,
		.inflated = 509,
		.compressed = false
	},
	{
		.name = "frame28t.tga",
		.addr = (void *) frame28t_tga_gz,
		.size = 514,
		.inflated = 514,
		.compressed = false
	},
	{
		.name = "frame29t.tga",
		.addr = (void *) frame29t_tga_gz,
		.size = 498,
		.inflated = 498,
		.compressed = false
	},
	{
		.name = "frame30t.tga",
		.addr = (void *) frame30t_tga_gz,
		.size = 509,
		.inflated = 509,
		.compressed = false
	}
};

size_t frame01t_tga_gz_size = 505;
size_t frame02t_tga_gz_size = 508;
size_t frame03t_tga_gz_size = 507;
size_t frame04t_tga_gz_size = 510;
size_t frame05t_tga_gz_size = 511;
size_t frame06t_tga_gz_size = 509;
size_t frame07t_tga_gz_size = 505;
size_t frame08t_tga_gz_size = 499;
size_t frame09t_tga_gz_size = 507;
size_t frame10t_tga_gz_size = 509;
size_t frame11t_tga_gz_size = 507;
size_t frame12t_tga_gz_size = 509;
size_t frame13t_tga_gz_size = 502;
size_t frame14t_tga_gz_size = 504;
size_t frame15t_tga_gz_size = 502;
size_t frame16t_tga_gz_size = 501;
size_t frame17t_tga_gz_size = 500;
size_t frame18t_tga_gz_size = 508;
size_t frame19t_tga_gz_size = 508;
size_t frame20t_tga_gz_size = 507;
size_t frame21t_tga_gz_size = 511;
size_t frame22t_tga_gz_size = 508;
size_t frame23t_tga_gz_size = 500;
size_t frame24t_tga_gz_size = 504;
size_t frame25t_tga_gz_size = 508;
size_t frame26t_tga_gz_size = 510;
size_t frame27t_tga_gz_size = 509;
size_t frame28t_tga_gz_size = 514;
size_t frame29t_tga_gz_size = 498;
size_t frame30t_tga_gz_size = 509;
