/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

#include "images.h"

image_t images[] = {
	{
		.name = "frame01.tga",
		.addr = (void *) frame01_tga_gz,
		.size = 16065,
		.inflated = 16065,
		.compressed = false
	},
	{
		.name = "frame02.tga",
		.addr = (void *) frame02_tga_gz,
		.size = 16044,
		.inflated = 16044,
		.compressed = false
	},
	{
		.name = "frame03.tga",
		.addr = (void *) frame03_tga_gz,
		.size = 15948,
		.inflated = 15948,
		.compressed = false
	},
	{
		.name = "frame04.tga",
		.addr = (void *) frame04_tga_gz,
		.size = 15891,
		.inflated = 15891,
		.compressed = false
	},
	{
		.name = "frame05.tga",
		.addr = (void *) frame05_tga_gz,
		.size = 15800,
		.inflated = 15800,
		.compressed = false
	},
	{
		.name = "frame06.tga",
		.addr = (void *) frame06_tga_gz,
		.size = 15803,
		.inflated = 15803,
		.compressed = false
	},
	{
		.name = "frame07.tga",
		.addr = (void *) frame07_tga_gz,
		.size = 15812,
		.inflated = 15812,
		.compressed = false
	},
	{
		.name = "frame08.tga",
		.addr = (void *) frame08_tga_gz,
		.size = 15670,
		.inflated = 15670,
		.compressed = false
	},
	{
		.name = "frame09.tga",
		.addr = (void *) frame09_tga_gz,
		.size = 15698,
		.inflated = 15698,
		.compressed = false
	},
	{
		.name = "frame10.tga",
		.addr = (void *) frame10_tga_gz,
		.size = 15748,
		.inflated = 15748,
		.compressed = false
	},
	{
		.name = "frame11.tga",
		.addr = (void *) frame11_tga_gz,
		.size = 15902,
		.inflated = 15902,
		.compressed = false
	},
	{
		.name = "frame12.tga",
		.addr = (void *) frame12_tga_gz,
		.size = 15945,
		.inflated = 15945,
		.compressed = false
	},
	{
		.name = "frame13.tga",
		.addr = (void *) frame13_tga_gz,
		.size = 16002,
		.inflated = 16002,
		.compressed = false
	},
	{
		.name = "frame14.tga",
		.addr = (void *) frame14_tga_gz,
		.size = 16210,
		.inflated = 16210,
		.compressed = false
	},
	{
		.name = "frame15.tga",
		.addr = (void *) frame15_tga_gz,
		.size = 16061,
		.inflated = 16061,
		.compressed = false
	},
	{
		.name = "frame16.tga",
		.addr = (void *) frame16_tga_gz,
		.size = 15991,
		.inflated = 15991,
		.compressed = false
	},
	{
		.name = "frame17.tga",
		.addr = (void *) frame17_tga_gz,
		.size = 16085,
		.inflated = 16085,
		.compressed = false
	},
	{
		.name = "frame18.tga",
		.addr = (void *) frame18_tga_gz,
		.size = 15940,
		.inflated = 15940,
		.compressed = false
	},
	{
		.name = "frame19.tga",
		.addr = (void *) frame19_tga_gz,
		.size = 15819,
		.inflated = 15819,
		.compressed = false
	},
	{
		.name = "frame20.tga",
		.addr = (void *) frame20_tga_gz,
		.size = 15805,
		.inflated = 15805,
		.compressed = false
	},
	{
		.name = "frame21.tga",
		.addr = (void *) frame21_tga_gz,
		.size = 15762,
		.inflated = 15762,
		.compressed = false
	},
	{
		.name = "frame22.tga",
		.addr = (void *) frame22_tga_gz,
		.size = 15711,
		.inflated = 15711,
		.compressed = false
	},
	{
		.name = "frame23.tga",
		.addr = (void *) frame23_tga_gz,
		.size = 15672,
		.inflated = 15672,
		.compressed = false
	},
	{
		.name = "frame24.tga",
		.addr = (void *) frame24_tga_gz,
		.size = 15717,
		.inflated = 15717,
		.compressed = false
	},
	{
		.name = "frame25.tga",
		.addr = (void *) frame25_tga_gz,
		.size = 15806,
		.inflated = 15806,
		.compressed = false
	},
	{
		.name = "frame26.tga",
		.addr = (void *) frame26_tga_gz,
		.size = 15924,
		.inflated = 15924,
		.compressed = false
	},
	{
		.name = "frame27.tga",
		.addr = (void *) frame27_tga_gz,
		.size = 15926,
		.inflated = 15926,
		.compressed = false
	},
	{
		.name = "frame28.tga",
		.addr = (void *) frame28_tga_gz,
		.size = 16041,
		.inflated = 16041,
		.compressed = false
	},
	{
		.name = "frame29.tga",
		.addr = (void *) frame29_tga_gz,
		.size = 16095,
		.inflated = 16095,
		.compressed = false
	},
	{
		.name = "frame30.tga",
		.addr = (void *) frame30_tga_gz,
		.size = 16021,
		.inflated = 16021,
		.compressed = false
	}
};

size_t frame01_tga_gz_size = 16065;
size_t frame02_tga_gz_size = 16044;
size_t frame03_tga_gz_size = 15948;
size_t frame04_tga_gz_size = 15891;
size_t frame05_tga_gz_size = 15800;
size_t frame06_tga_gz_size = 15803;
size_t frame07_tga_gz_size = 15812;
size_t frame08_tga_gz_size = 15670;
size_t frame09_tga_gz_size = 15698;
size_t frame10_tga_gz_size = 15748;
size_t frame11_tga_gz_size = 15902;
size_t frame12_tga_gz_size = 15945;
size_t frame13_tga_gz_size = 16002;
size_t frame14_tga_gz_size = 16210;
size_t frame15_tga_gz_size = 16061;
size_t frame16_tga_gz_size = 15991;
size_t frame17_tga_gz_size = 16085;
size_t frame18_tga_gz_size = 15940;
size_t frame19_tga_gz_size = 15819;
size_t frame20_tga_gz_size = 15805;
size_t frame21_tga_gz_size = 15762;
size_t frame22_tga_gz_size = 15711;
size_t frame23_tga_gz_size = 15672;
size_t frame24_tga_gz_size = 15717;
size_t frame25_tga_gz_size = 15806;
size_t frame26_tga_gz_size = 15924;
size_t frame27_tga_gz_size = 15926;
size_t frame28_tga_gz_size = 16041;
size_t frame29_tga_gz_size = 16095;
size_t frame30_tga_gz_size = 16021;
