/*
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/mkarray.py
 */

#ifndef IMAGE_TINYS_H_
#define IMAGE_TINYS_H_

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#define IMAGE_TINYS  30

#ifndef IMAGES_T_
#define IMAGES_T_

typedef struct {
	const char *name;
	void *addr;
	size_t size;
	size_t inflated;
	bool compressed;
} image_t;

#endif
extern image_t image_tinys[];

extern uint8_t frame01t_tga_gz[];
extern size_t frame01t_tga_gz_size;
extern uint8_t frame02t_tga_gz[];
extern size_t frame02t_tga_gz_size;
extern uint8_t frame03t_tga_gz[];
extern size_t frame03t_tga_gz_size;
extern uint8_t frame04t_tga_gz[];
extern size_t frame04t_tga_gz_size;
extern uint8_t frame05t_tga_gz[];
extern size_t frame05t_tga_gz_size;
extern uint8_t frame06t_tga_gz[];
extern size_t frame06t_tga_gz_size;
extern uint8_t frame07t_tga_gz[];
extern size_t frame07t_tga_gz_size;
extern uint8_t frame08t_tga_gz[];
extern size_t frame08t_tga_gz_size;
extern uint8_t frame09t_tga_gz[];
extern size_t frame09t_tga_gz_size;
extern uint8_t frame10t_tga_gz[];
extern size_t frame10t_tga_gz_size;
extern uint8_t frame11t_tga_gz[];
extern size_t frame11t_tga_gz_size;
extern uint8_t frame12t_tga_gz[];
extern size_t frame12t_tga_gz_size;
extern uint8_t frame13t_tga_gz[];
extern size_t frame13t_tga_gz_size;
extern uint8_t frame14t_tga_gz[];
extern size_t frame14t_tga_gz_size;
extern uint8_t frame15t_tga_gz[];
extern size_t frame15t_tga_gz_size;
extern uint8_t frame16t_tga_gz[];
extern size_t frame16t_tga_gz_size;
extern uint8_t frame17t_tga_gz[];
extern size_t frame17t_tga_gz_size;
extern uint8_t frame18t_tga_gz[];
extern size_t frame18t_tga_gz_size;
extern uint8_t frame19t_tga_gz[];
extern size_t frame19t_tga_gz_size;
extern uint8_t frame20t_tga_gz[];
extern size_t frame20t_tga_gz_size;
extern uint8_t frame21t_tga_gz[];
extern size_t frame21t_tga_gz_size;
extern uint8_t frame22t_tga_gz[];
extern size_t frame22t_tga_gz_size;
extern uint8_t frame23t_tga_gz[];
extern size_t frame23t_tga_gz_size;
extern uint8_t frame24t_tga_gz[];
extern size_t frame24t_tga_gz_size;
extern uint8_t frame25t_tga_gz[];
extern size_t frame25t_tga_gz_size;
extern uint8_t frame26t_tga_gz[];
extern size_t frame26t_tga_gz_size;
extern uint8_t frame27t_tga_gz[];
extern size_t frame27t_tga_gz_size;
extern uint8_t frame28t_tga_gz[];
extern size_t frame28t_tga_gz_size;
extern uint8_t frame29t_tga_gz[];
extern size_t frame29t_tga_gz_size;
extern uint8_t frame30t_tga_gz[];
extern size_t frame30t_tga_gz_size;

#endif
